sudo: required
services:
  - docker
  
before_install:
  - docker build -t kalpeshkhune/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true kalpeshkhune/docker-react npm run test

language: generic 