sudo: required
services:
  - docker
  
before_install:
  - docker build -t kalpeshkhune/docker-react -f Dockerfile.dev .
  
script:
  - docker run kalpeshkhune/docker-react npm run test -- --coverage
   