sudo: required
services:
  - docker
  
before_install:
  - docker build -t kalpeshkhune/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true kalpeshkhune/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-505294226570"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

